blank_issues_enabled: false
contact_links:
  - name: "Talk to us on the Poseidon Framework's Gitter"
    url: https://app.gitter.im/#/room/!TycQipeBdEPTHWqilU:gitter.im
    about: Discussions about everything Poseidon-Framework.
